name: project_money
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  colornames: ^0.1.0
  google_fonts: ^6.1.0
  file_picker: ^5.5.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  uuid:
  copy_with_extension: ^5.0.4
  states_rebuilder: ^6.3.0
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  isar_generator: 3.1.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
# dart run flutter_launcher_icons
 